### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by lxtGH** [NaiyuGao/PanopticDepth#1]
Hi! It is a great work on Panoptic Depth. 

Our work is very closely to your work.  But we take a further step using query to unify all sub-tasks for DVPS task including DPS + Video. 

https://arxiv.org/abs/2112.02582 (11.2021 on arxiv). 

Would you like to give us a citation. 

We will cite your work in our updated draft.

**Comment by NaiyuGao** [comment]
@lxtGH PolyphonicForm is a great work that unifies panoptic segmentation, depth estimation, and tracking. But unfortunately, we may not be able to cite your work because the camera-ready version was uploaded two months ago.
